server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://121.43.101.99:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: mall
    password: 123456mjz...
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: jhzz-mall-learnning


mybatis:
  mapper-locations:
    - classpath: mapper/*.xml
    - classpath*: com/**/mapper/*.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
